import { stateTypes } from '../reducers';
export const getLeftWidth = (state: stateTypes) => state.app.leftWidth;
export const getMiddleWidth = (state: stateTypes) => state.app.middleWidth;
export const getDialogType = (state: stateTypes) => state.app.dialogType;
export const getSort = (state: stateTypes) => state.app.sort;
export const getIsEdit = (state: stateTypes) => state.app.isEdit;
export const getIsEye = (state: stateTypes) => state.app.isEye;
export const getCheckMenu = (state: stateTypes) => state.app.checkMenu;
export const getCheckNotes = (state: stateTypes) => state.app.checkNotes;
export const getNotes = (state: stateTypes) => state.app.notes;
export const getSearch = (state: stateTypes) => state.app.search;
export const getLeftLoading = (state: stateTypes) => state.app.leftLoading;
export const getMiddleLoading = (state: stateTypes) => state.app.middleLoading;
export const getMainLoading = (state: stateTypes) => state.app.mainLoading;
